---
name: Bot Approval 🤖

on:
  pull_request:
    branches:
      - main

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    name: Approve ✅
    steps:
      - name: Auto Approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          review-message: "LGTM 🤖"
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
